### ISSUE TITLE
TypeError: Request with GET/HEAD method cannot have body

### ISSUE THREAD

**Issue by bengavrilov** [castle/castle-node#122] opened 2021-08-12 22:36 UTC
Here is how to reproduce:
```typescript
import { Castle } from '@castleio/sdk';
const castle = new Castle({ apiSecret: api_key });
const devices = await castle.getDevicesForUser({ user_id:  id });
```

I noticed a fix was already published in the `develop` branch. Any update on how long it may take to be released?

**Comment by cibergarri** [comment] 2021-09-15 09:21
I have the same issue when calling  `castle.getDevice`

**Comment by cibergarri** [comment] 2021-09-15 09:25
I think the issue is the release 1.0.3 has not been created yet @reneechar

**Comment by bartes** [comment] 2021-09-15 18:23
Thank you for pointing that out 👍 . The 1.0.3 version should be available in the npm registry.

I'm closing the issue.  Please reopen or create the new one if you notice any problem with the fix.

**Closed by bartes** 2021-09-15 18:23 UTC

**Comment by cibergarri** [comment] 2021-09-15 20:32
Thank you @bartes!!
